### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by goldendel** [dirkfabisch/Dxtr#15]
Hello, 

I'm not a coder but I would like to help the development of this app somehow.  Would it help to get a list of the skills you need so we can go to market for the skills and maybe back it with a crowdsourcing campaign?  There must be a lot of iOS users wanting to upload to Nightscout.

Let me know if this would help.

Tim

**Comment by dirkfabisch** [comment]
Hi Tim,

thanks for your offer. I really appreciate any support. Unfortunately I have no time for this project, because of my work. In the actual state it will make no sense ask for help, because I have to do a lot of cleanup and housekeeping in the code, so that some one else can join me in the development. Hopefully in in a couple of weeks I will be abel to continue on Dxtr, because it is really important for me.

.dirk

**Comment by goldendel** [comment]
Hi Dirk,

I understand completely.  I'm in a similar boat to you, just not in development.  Shout out when you're ready and I'll do what I can.

Tim
